version: '3.8'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  worker:
    build: .
    command: celery -A app.workers.video_tasks.celery worker --loglevel=info
    depends_on:
      - redis
